language: node_js
sudo: required
services:
- docker
env:
- SH="docker exec -t http-prauksy bash -c"
addons:
  apt:
    update: true
    packages:
    - unzip
  on:
    branch: master
before_install:
- docker run --detach --name http-prauksy -v $(pwd):/travis -w /travis node:8-stretch-slim
  tail -f /dev/null
- docker ps
install:
- npm install
script: skip
after_failure:
- curl -X POST -d 'message="http-prauksy build failed"' https://${HOME_API_USER}:${HOME_API_AUTHKEY}@${REMOTE_SERVER}/api/pushover
after_success:
- curl -X POST -d 'message="http-prauksy build successful"' https://${HOME_API_USER}:${HOME_API_AUTHKEY}@${REMOTE_SERVER}/api/pushover
before_deploy:
- curl -L -o deploy.zip https://www.dropbox.com/sh/ey98rnmbap1qa9u/AAC5xPjmktekZunXVOMMTPaNa?dl=0
- unzip deploy.zip -x /
- openssl aes-256-cbc -K $encrypted_50a234098985_key -iv $encrypted_50a234098985_iv -in secret.txt.enc -out secret.txt -d
- $SH "npm run bundle"
- which ssh-agent || ( sudo apt-get update -qy && apt-get install --no-install-recommends -qfy openssh-client git )
- mkdir -p ~/.ssh
- mv secret.txt ~/.ssh/id_rsa
- sudo chmod 600 ~/.ssh/id_rsa
- ssh-keyscan -H $REMOTE_SERVER > ~/.ssh/known_hosts
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
